/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.wordnik.sample.model

import com.wordnik.swagger.runtime.annotations._

import scala.reflect.BeanProperty

import scala.collection.JavaConversions._

import scala.collection.mutable.ListBuffer


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author tony
 *
 */
class Pet extends Object {

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var id:Long =_

	/**
	 * 
	 * 
	 * 
	 */
	var tags  =  new ListBuffer[Tag]
	def getTags:java.util.List[com.wordnik.sample.model.Tag] = {
	    tags.toList
	}
	def setTags(args:java.util.List[com.wordnik.sample.model.Tag]) = {
	    tags.clear
	    args.foreach(arg=>tags += arg)
	}

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var category:Category =_

	/**
	 * pet status in the store
	 * 
	 * 
	 */
    @BeanProperty
    var status:String =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var name:String =_

	/**
	 * 
	 * 
	 * 
	 */
	var photoUrls  =  new ListBuffer[String]
	def getPhotoUrls:java.util.List[String] = {
	    photoUrls.toList
	}
	def setPhotoUrls(args:java.util.List[String]) = {
	    photoUrls.clear
	    args.foreach(arg=>photoUrls += arg)
	}

    override def toString:String = {
        "[" +
        "id:" + id + 
            "tags:" + tags + 
            "category:" + category + 
            "status:" + status + 
            "name:" + name + 
            "photoUrls:" + photoUrls + "]"
    }
}