/**
 *  Copyright 2012 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.wordnik.api.client.model


/**
 * 
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 * @author tony
 *
 */
object IncludePartOfSpeechValues {
    var Noun = "noun"
    var Adjective = "adjective"
    var Verb = "verb"
    var Adverb = "adverb"
    var Interjection = "interjection"
    var Pronoun = "pronoun"
    var Preposition = "preposition"
    var Abbreviation = "abbreviation"
    var Affix = "affix"
    var Article = "article"
    var Auxiliary_verb = "auxiliary-verb"
    var Conjunction = "conjunction"
    var Definite_article = "definite-article"
    var Family_name = "family-name"
    var Given_name = "given-name"
    var Idiom = "idiom"
    var Imperative = "imperative"
    var Noun_plural = "noun-plural"
    var Noun_posessive = "noun-posessive"
    var Past_participle = "past-participle"
    var Phrasal_prefix = "phrasal-prefix"
    var Proper_noun = "proper-noun"
    var Proper_noun_plural = "proper-noun-plural"
    var Proper_noun_posessive = "proper-noun-posessive"
    var Suffix = "suffix"
    var Verb_intransitive = "verb-intransitive"
    var Verb_transitive = "verb-transitive"
}