/**
 *  Copyright 2012 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
package com.wordnik.api.client.model

import com.wordnik.swagger.runtime.annotations._

import scala.reflect.BeanProperty

import scala.collection.JavaConversions._


/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 * @author tony
 *
 */
class ScoredWord extends Object {

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var id:Long =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var position:Integer =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var lemma:String =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var docTermCount:Integer =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var wordType:String =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var score:Float =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var word:String =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var sentenceId:Long =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var stopword:Boolean =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var baseWordScore:Double =_

	/**
	 * 
	 * 
	 * 
	 */
    @BeanProperty
    var partOfSpeech:String =_

    override def toString:String = {
        "[" +
        "id:" + id + 
            "position:" + position + 
            "lemma:" + lemma + 
            "docTermCount:" + docTermCount + 
            "wordType:" + wordType + 
            "score:" + score + 
            "word:" + word + 
            "sentenceId:" + sentenceId + 
            "stopword:" + stopword + 
            "baseWordScore:" + baseWordScore + 
            "partOfSpeech:" + partOfSpeech + "]"
    }
}